name: smart_documents_scanner
description: "Application for scanning and analysing documents"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  easy_localization: 3.0.8
  camera: 0.11.0
  path_provider: 2.1.2
  google_mlkit_text_recognition: 0.13.0
  flutter_bloc: 8.1.3
  equatable: 2.0.5
  uuid: 4.4.2
  image_picker: 1.2.1
  photo_manager: 3.8.3
  auto_route: 10.3.0
  drift: 2.30.1
  sqlite3_flutter_libs: 0.5.28
  permission_handler: 12.0.1
  share_plus: 12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  build_runner: 2.7.1
  drift_dev: 2.30.0
  source_gen: 3.1.0
  auto_route_generator: 10.3.0
  analyzer: 8.3.0
  mocktail: 1.0.4
  bloc_test: 9.1.7
  test_cov: 1.0.1
  transparent_image: 2.0.1
  flutter_launcher_icons: 0.14.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/translations/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
